# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Doctor3.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 700, 600))
        self.tabWidget.setObjectName("tabWidget")
        self.Visit = QtWidgets.QWidget()
        self.Visit.setObjectName("Visit")
        self.btnPatient = QtWidgets.QPushButton(self.Visit)
        self.btnPatient.setGeometry(QtCore.QRect(395, 7, 100, 30))
        self.btnPatient.setObjectName("btnPatient")
        self.btnDiag = QtWidgets.QPushButton(self.Visit)
        self.btnDiag.setGeometry(QtCore.QRect(450, 170, 120, 30))
        self.btnDiag.setObjectName("btnDiag")
        self.btnDrug = QtWidgets.QPushButton(self.Visit)
        self.btnDrug.setGeometry(QtCore.QRect(450, 220, 120, 30))
        self.btnDrug.setObjectName("btnDrug")
        self.btnCrReceipt = QtWidgets.QPushButton(self.Visit)
        self.btnCrReceipt.setGeometry(QtCore.QRect(510, 380, 120, 35))
        self.btnCrReceipt.setObjectName("btnCrReceipt")
        self.txtTZ = QtWidgets.QTextEdit(self.Visit)
        self.txtTZ.setGeometry(QtCore.QRect(80, 10, 271, 21))
        self.txtTZ.setObjectName("txtTZ")
        self.textEdit_3 = QtWidgets.QTextEdit(self.Visit)
        self.textEdit_3.setGeometry(QtCore.QRect(160, 210, 250, 40))
        self.textEdit_3.setObjectName("textEdit_3")
        self.txtData = QtWidgets.QPlainTextEdit(self.Visit)
        self.txtData.setGeometry(QtCore.QRect(100, 40, 291, 21))
        self.txtData.setObjectName("txtData")
        self.listDiagnoses = QtWidgets.QListWidget(self.Visit)
        self.listDiagnoses.setGeometry(QtCore.QRect(0, 90, 221, 71))
        self.listDiagnoses.setObjectName("listDiagnoses")
        self.lstGrugs = QtWidgets.QListWidget(self.Visit)
        self.lstGrugs.setGeometry(QtCore.QRect(250, 90, 221, 71))
        self.lstGrugs.setObjectName("lstGrugs")
        self.label = QtWidgets.QLabel(self.Visit)
        self.label.setGeometry(QtCore.QRect(14, 10, 61, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Visit)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 85, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.Visit)
        self.label_3.setGeometry(QtCore.QRect(0, 70, 201, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.Visit)
        self.label_4.setGeometry(QtCore.QRect(250, 70, 261, 16))
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(self.Visit)
        self.comboBox.setGeometry(QtCore.QRect(160, 171, 181, 31))
        self.comboBox.setObjectName("comboBox")
        self.label_5 = QtWidgets.QLabel(self.Visit)
        self.label_5.setGeometry(QtCore.QRect(10, 180, 101, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.Visit)
        self.label_6.setGeometry(QtCore.QRect(10, 210, 201, 16))
        self.label_6.setObjectName("label_6")
        self.tblResult = QtWidgets.QTableWidget(self.Visit)
        self.tblResult.setGeometry(QtCore.QRect(10, 320, 420, 231))
        self.tblResult.setObjectName("tblResult")
        self.tblResult.setColumnCount(0)
        self.tblResult.setRowCount(0)
        self.label_7 = QtWidgets.QLabel(self.Visit)
        self.label_7.setGeometry(QtCore.QRect(40, 275, 200, 31))
        self.label_7.setObjectName("label_7")
        self.tabWidget.addTab(self.Visit, "")
        self.reports = QtWidgets.QWidget()
        self.reports.setObjectName("reports")
        self.tabWidget.addTab(self.reports, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnPatient.setText(_translate("MainWindow", "Find Patient"))
        self.btnDiag.setText(_translate("MainWindow", "add Diagnose"))
        self.btnDrug.setText(_translate("MainWindow", "check Drug"))
        self.btnCrReceipt.setText(_translate("MainWindow", "Create Receipt"))
        self.label.setText(_translate("MainWindow", "Insert tz of Patient"))
        self.label_2.setText(_translate("MainWindow", "Patient data"))
        self.label_3.setText(_translate("MainWindow", "List of Chronic Diseases"))
        self.label_4.setText(_translate("MainWindow", "List Of Constant Drug Treatment"))
        self.label_5.setText(_translate("MainWindow", "new Diagnose"))
        self.label_6.setText(_translate("MainWindow", "New suggested drug"))
        self.label_7.setText(_translate("MainWindow", "Check Interaction result"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Visit), _translate("MainWindow", "Visit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.reports), _translate("MainWindow", "Reports"))

    def add_func(self):
        self.btnDrug.clicked.connect(lambda: self.checkDrug(self.textEdit_3.text()))
        self.btnPatient.clicked.connect(lambda: self.findPatient(self.txtTZ.text()))
        self.btnDiag.clicked.connect(lambda: self.addDiagnose(self.comboBox.text()))
        self.btnCrReceipt.clicked.connect(lambda: self.createReceipt(self))

    def findPatient(tz):
        pass
    def checkDrug(drugName):
        pass

    def createReceipt(self):
        pass

    def addDiagnose(name):
        pass
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
